CREATE DATABASE
IF NOT EXISTS DDTAXI;

USE DDTAXI;

CREATE TABLE
IF NOT EXISTS CLIENT (
	编号 INT AUTO_INCREMENT PRIMARY KEY,
	密码 VARCHAR (16) NOT NULL,
	手机号码 VARCHAR (11) NOT NULL,
	当前状态 TINYINT DEFAULT 0,
	当前经度 TINYINT DEFAULT NULL,
	当前纬度 TINYINT DEFAULT NULL,
	账户余额 INT DEFAULT 0,
	支付密码 VARCHAR (6) NOT NULL
) DEFAULT CHARSET = UTF8;

CREATE TABLE
IF NOT EXISTS DRIVER (
	编号 INT AUTO_INCREMENT PRIMARY KEY,
	密码 VARCHAR (16) NOT NULL,
	手机号码 VARCHAR (11) NOT NULL,
	公司 VARCHAR (20),
	准驾证号 VARCHAR (15) NOT NULL,
	车牌号 VARCHAR (10) NOT NULL,
	当前状态 TINYINT DEFAULT 0,
	当前经度 TINYINT DEFAULT NULL,
	当前纬度 TINYINT DEFAULT NULL,
	账户余额 INT DEFAULT 0,
	提现密码 VARCHAR (6) NOT NULL
) CHARSET = UTF8;

CREATE TABLE
IF NOT EXISTS ORD(
	客户编号 INT NOT NULL,
	起点 VARCHAR (20),
	终点 VARCHAR (20),
	时间 DATETIME,
	司机编号 INT,
	费用 INT,
	状态 TINYINT DEFAULT 0,
	PRIMARY KEY (客户编号, 司机编号),
	FOREIGN KEY (客户编号) REFERENCES CLIENT (编号) ON DELETE CASCADE,
	FOREIGN KEY (司机编号) REFERENCES DRIVER (编号) ON DELETE CASCADE
) CHARSET = UTF8;